### ISSUE TITLE
Tips for Rspec

### ISSUE THREAD

**Issue by davithss** [learn-co-curriculum/apis-and-faraday-reading#10]
Hello, great article.
Can you give me some tips on how to spec this?
I'm creating a full integration using  faraday and I need to make specs using Rspec.

Thanks.

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
